# Generated by Django 4.0.3 on 2022-03-22 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_bu',
            },
        ),
        migrations.CreateModel(
            name='Carrier_result',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('carrier_number', models.CharField(max_length=255, null=True)),
                ('time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'tbl_carrier_result',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('image_url', models.CharField(max_length=255, null=True)),
                ('spec_url', models.CharField(max_length=255, null=True)),
                ('direction', models.CharField(max_length=255, null=True)),
                ('layout', models.CharField(max_length=255, null=True)),
                ('material_number', models.CharField(max_length=255, null=True)),
                ('distance_to_nearest_component', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('image_on_sop_url', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_component',
            },
        ),
        migrations.CreateModel(
            name='Component_Result',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(null=True)),
                ('date_code', models.CharField(max_length=10, null=True)),
                ('material_number', models.CharField(max_length=25, null=True)),
                ('lot_code', models.CharField(max_length=10, null=True)),
                ('roi_x', models.IntegerField(null=True)),
                ('roi_y', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.component')),
            ],
            options={
                'db_table': 'tbl_component_result',
            },
        ),
        migrations.CreateModel(
            name='Inspection_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_inspection_image',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preheat_method', models.CharField(max_length=255, null=True)),
                ('solder_type', models.CharField(max_length=255, null=True)),
                ('ping_time', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('sfis_name', models.CharField(max_length=15, null=True)),
                ('bu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.bu')),
            ],
            options={
                'db_table': 'tbl_line',
            },
        ),
        migrations.CreateModel(
            name='Line_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(null=True, upload_to='images')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.line')),
            ],
            options={
                'db_table': 'tbl_line_model',
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_machine_type',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasheet_url', models.CharField(max_length=255, null=True)),
                ('spec_img_url', models.CharField(max_length=255, null=True)),
                ('dimension_url1', models.CharField(max_length=255, null=True)),
                ('dimension_url2', models.CharField(max_length=255, null=True)),
                ('dimension_url3', models.CharField(max_length=255, null=True)),
                ('schematic_img_url', models.CharField(max_length=255, null=True)),
                ('material_number', models.CharField(max_length=255, null=True)),
                ('dataset_url', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_material',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('thinkness', models.CharField(max_length=255, null=True)),
                ('surface_type', models.CharField(max_length=255, null=True)),
                ('image_url', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_model',
            },
        ),
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.machinetype')),
            ],
            options={
                'db_table': 'tbl_params',
            },
        ),
        migrations.CreateModel(
            name='Params_data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField(null=True)),
                ('time', models.DateTimeField(null=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.line')),
                ('params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.params')),
            ],
            options={
                'db_table': 'tbl_params_data',
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lsl', models.CharField(max_length=255)),
                ('usl', models.CharField(max_length=255)),
                ('line_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.line_model')),
                ('params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.params')),
            ],
            options={
                'db_table': 'tbl_spec',
            },
        ),
        migrations.CreateModel(
            name='Solder_Point_Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_shape', models.CharField(max_length=255, null=True)),
                ('pad_shape', models.CharField(max_length=255, null=True)),
                ('hole_size', models.CharField(max_length=255, null=True)),
                ('pad_size', models.CharField(max_length=255, null=True)),
                ('index', models.IntegerField(null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.component')),
            ],
            options={
                'db_table': 'tbl_solder_point_specification',
            },
        ),
        migrations.CreateModel(
            name='Pin_infor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(null=True)),
                ('dimension', models.CharField(max_length=255, null=True)),
                ('index', models.IntegerField(null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.material')),
            ],
            options={
                'db_table': 'tbl_pin_infor',
            },
        ),
        migrations.CreateModel(
            name='PCB_result',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sn', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=5, null=True)),
                ('carrier_number', models.CharField(max_length=25, null=True)),
                ('pcb_index', models.IntegerField(null=True)),
                ('material_number', models.CharField(max_length=25, null=True)),
                ('date_code', models.CharField(max_length=15, null=True)),
                ('pcb_desc', models.CharField(max_length=100, null=True)),
                ('lot_code', models.CharField(max_length=15, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('line', models.CharField(max_length=255, null=True)),
                ('smt_to_pth', models.IntegerField(null=True)),
                ('insp2_to_pth', models.IntegerField(null=True)),
                ('carrier_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pth.carrier_result')),
                ('line_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.line_model')),
            ],
            options={
                'db_table': 'tbl_pcb_result',
            },
        ),
        migrations.CreateModel(
            name='PCB_component_pin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=5, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('error_code', models.CharField(max_length=25, null=True)),
                ('roi_x', models.IntegerField(null=True)),
                ('roi_y', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('angle', models.FloatField(null=True)),
                ('line', models.CharField(max_length=255, null=True)),
                ('model', models.CharField(max_length=255, null=True)),
                ('component_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.component_result')),
            ],
            options={
                'db_table': 'tbl_pcb_component_pin',
            },
        ),
        migrations.CreateModel(
            name='Params_settings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField(null=True)),
                ('time', models.DateTimeField(null=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.line')),
                ('params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.params')),
            ],
            options={
                'db_table': 'tbl_params_setting',
            },
        ),
        migrations.CreateModel(
            name='Params_Of_PCB',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('min', models.FloatField(null=True)),
                ('max', models.FloatField(null=True)),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.params')),
                ('pcb_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.pcb_result')),
            ],
            options={
                'db_table': 'tbl_params_of_pcb',
            },
        ),
        migrations.CreateModel(
            name='Params_Detail_Of_PCB',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.params')),
                ('param_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.params_data')),
                ('pcb_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.pcb_result')),
            ],
            options={
                'db_table': 'tbl_params_detail_of_pcb',
            },
        ),
        migrations.AddField(
            model_name='params_data',
            name='setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pth.params_settings'),
        ),
        migrations.AddField(
            model_name='line_model',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.model'),
        ),
        migrations.AddField(
            model_name='component_result',
            name='inspection_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.inspection_image'),
        ),
        migrations.AddField(
            model_name='component_result',
            name='pcb_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.pcb_result'),
        ),
        migrations.AddField(
            model_name='component',
            name='materials',
            field=models.ManyToManyField(to='pth.material'),
        ),
        migrations.AddField(
            model_name='component',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.model'),
        ),
        migrations.CreateModel(
            name='Carrier_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('bu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pth.bu')),
            ],
            options={
                'db_table': 'tbl_carrier_code',
            },
        ),
    ]
